import { Azeret_Mono } from 'next/font/google'
import './globals.css'

const mono = Azeret_Mono({ subsets: ['latin'],weight:['400'],})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={mono.className}>
      {props.children}
      
      </body>
    </html>
  )
}
